// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(apiKey: 'REPLACE_WITH_YOUR_ANDROID_API_KEY', appId: 'REPLACE_WITH_YOUR_ANDROID_APP_ID', messagingSenderId: 'REPLACE_WITH_YOUR_MESSAGING_SENDER_ID', projectId: 'REPLACE_WITH_YOUR_PROJECT_ID', storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET');

  static const FirebaseOptions ios = FirebaseOptions(apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY', appId: 'REPLACE_WITH_YOUR_IOS_APP_ID', messagingSenderId: 'REPLACE_WITH_YOUR_MESSAGING_SENDER_ID', projectId: 'REPLACE_WITH_YOUR_PROJECT_ID', storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET', androidClientId: 'REPLACE_WITH_YOUR_ANDROID_CLIENT_ID', iosClientId: 'REPLACE_WITH_YOUR_IOS_CLIENT_ID', iosBundleId: 'REPLACE_WITH_YOUR_IOS_BUNDLE_ID');
}
